# Generated by Django 5.2.8 on 2025-12-05 01:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acontecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dataAcontecimento', models.DateField(blank=True, null=True, verbose_name='Data do Acontecimento')),
                ('risco', models.CharField(blank=True, max_length=45, null=True, verbose_name='Risco')),
            ],
            options={
                'verbose_name': 'Acontecimento',
                'verbose_name_plural': 'Acontecimentos',
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resumo')),
                ('dataPublicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
        migrations.CreateModel(
            name='Desastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Desastre',
                'verbose_name_plural': 'Desastres',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('descricao_detalhada', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('desenvolvedor', models.CharField(default='A Crise G Studios', max_length=100, verbose_name='Desenvolvedor')),
                ('plataformas', models.CharField(default='Windows, Android, iOS', max_length=200, verbose_name='Plataformas')),
                ('idade_recomendada', models.CharField(default='12+ anos', max_length=50, verbose_name='Idade Recomendada')),
                ('tamanho', models.CharField(default='850MB (PC) / 320MB (Mobile)', max_length=50, verbose_name='Tamanho')),
                ('versao', models.CharField(default='1.3.2', max_length=20, verbose_name='Versão')),
                ('download_windows', models.URLField(blank=True, null=True, verbose_name='Link Download Windows')),
                ('download_android', models.URLField(blank=True, null=True, verbose_name='Link Download Android')),
                ('download_ios', models.URLField(blank=True, null=True, verbose_name='Link Download iOS')),
                ('imagem_capa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagem de Capa')),
                ('data_lancamento', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('jogadores_ativos', models.IntegerField(default=50000, verbose_name='Jogadores Ativos')),
                ('avaliacao_media', models.DecimalField(decimal_places=1, default=4.8, max_digits=3, verbose_name='Avaliação Média')),
                ('tempo_jogo_medio', models.CharField(default='12h', max_length=20, verbose_name='Tempo de Jogo Médio')),
                ('aprendizado_efetivo', models.CharField(default='95%', max_length=20, verbose_name='Aprendizado Efetivo')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('imagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagem')),
                ('tipo', models.CharField(blank=True, default='usuario', max_length=45, null=True, verbose_name='Tipo')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL da Imagem')),
                ('legenda', models.TextField(blank=True, null=True, verbose_name='Legenda')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Imagem do Jogo',
                'verbose_name_plural': 'Imagens do Jogo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FAQJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível no Site')),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('tecnico', 'Técnico'), ('jogabilidade', 'Jogabilidade'), ('pedagogico', 'Pedagógico'), ('outros', 'Outros')], default='geral', max_length=50, verbose_name='Categoria')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.jogo')),
            ],
            options={
                'verbose_name': 'FAQ do Jogo',
                'verbose_name_plural': 'FAQs do Jogo',
                'ordering': ['ordem', 'categoria', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='fas fa-check-circle', max_length=50, verbose_name='Ícone')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Característica do Jogo',
                'verbose_name_plural': 'Características do Jogo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20, verbose_name='Versão')),
                ('data', models.DateField(verbose_name='Data da Atualização')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Atualização do Jogo',
                'verbose_name_plural': 'Atualizações do Jogo',
                'ordering': ['-data', '-ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('acontecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.acontecimento', verbose_name='Acontecimento')),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.artigo', verbose_name='Artigo')),
                ('desastre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.desastre', verbose_name='Desastre')),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='RequisitoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('minimo', 'Mínimo'), ('recomendado', 'Recomendado')], default='minimo', max_length=20)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Requisito do Jogo',
                'verbose_name_plural': 'Requisitos do Jogo',
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nivel', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nível')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desastre', verbose_name='Desastre Relacionado')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
            },
        ),
        migrations.CreateModel(
            name='TopicoArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artigo', verbose_name='Artigo')),
            ],
            options={
                'verbose_name': 'Tópico do Artigo',
                'verbose_name_plural': 'Tópicos dos Artigos',
            },
        ),
        migrations.CreateModel(
            name='TopicoDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Tópico do Desastre',
                'verbose_name_plural': 'Tópicos dos Desastres',
            },
        ),
        migrations.CreateModel(
            name='PerguntaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('email', models.EmailField(max_length=254, verbose_name='Email para Resposta')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('arquivada', 'Arquivada'), ('publicada', 'Publicada como FAQ')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta_admin', models.TextField(blank=True, null=True, verbose_name='Resposta do Admin')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_usuarios', to='app.jogo', verbose_name='Jogo')),
                ('publicado_como_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.faqjogo', verbose_name='Publicado como FAQ')),
                ('admin_respondeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_respondidas', to='app.usuario', verbose_name='Admin que Respondeu')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_enviadas', to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta do Usuário',
                'verbose_name_plural': 'Perguntas dos Usuários',
                'ordering': ['-data_envio', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('horario', models.DateTimeField(auto_now_add=True, verbose_name='Horário')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo', verbose_name='Jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario', verbose_name='Autor'),
        ),
    ]
