# Generated by Django 5.2.8 on 2025-12-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
    ]
