# Generated by Django 5.2.8 on 2025-12-05 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visao_geral_completa', models.TextField(help_text='Descrição detalhada do desastre', verbose_name='Visão Geral Completa')),
                ('causas', models.TextField(help_text='Liste as causas principais, uma por linha', verbose_name='Causas')),
                ('medidas_prevencao', models.TextField(help_text='Descreva as medidas de prevenção', verbose_name='Medidas de Prevenção')),
                ('durante_desastre', models.TextField(help_text='Instruções para durante o desastre', verbose_name='O que fazer durante')),
                ('informacoes_tecnicas', models.JSONField(blank=True, default=dict, help_text='JSON com dados técnicos', null=True, verbose_name='Informações Técnicas')),
                ('fatos_historicos', models.JSONField(blank=True, default=list, help_text='Lista de fatos históricos em JSON', null=True, verbose_name='Fatos Históricos')),
                ('recursos_adicionais', models.JSONField(blank=True, default=list, help_text='Lista de recursos em JSON', null=True, verbose_name='Recursos Adicionais')),
                ('frequencia_global', models.CharField(default='Varia conforme o tipo', max_length=100, verbose_name='Frequência Global')),
                ('areas_risco', models.TextField(help_text='Principais áreas de risco no mundo', verbose_name='Áreas de Risco')),
                ('parametros_simulador', models.JSONField(blank=True, default=dict, null=True, verbose_name='Parâmetros do Simulador')),
                ('imagem_principal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagem Principal')),
                ('desastre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Detalhe do Desastre',
                'verbose_name_plural': 'Detalhes dos Desastres',
            },
        ),
        migrations.CreateModel(
            name='EventoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('magnitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Magnitude/Intensidade')),
                ('vitimas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vítimas/Danos')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_historicos', to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Evento Histórico',
                'verbose_name_plural': 'Eventos Históricos',
                'ordering': ['-data', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ImagemDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL da Imagem')),
                ('legenda', models.TextField(blank=True, null=True, verbose_name='Legenda')),
                ('tipo', models.CharField(choices=[('prevencao', 'Prevenção'), ('impacto', 'Impacto'), ('recuperacao', 'Recuperação'), ('educativo', 'Educativo')], default='impacto', max_length=50, verbose_name='Tipo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Imagem do Desastre',
                'verbose_name_plural': 'Imagens dos Desastres',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PrevencaoDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Medida')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('icone', models.CharField(default='fas fa-shield-alt', max_length=100, verbose_name='Ícone')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevencoes', to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Prevenção de Desastre',
                'verbose_name_plural': 'Prevenções de Desastres',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RecursoDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('guia', 'Guia/Manual'), ('mapa', 'Mapa'), ('video', 'Vídeo'), ('aplicativo', 'Aplicativo'), ('relatorio', 'Relatório'), ('ferramenta', 'Ferramenta')], default='guia', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL')),
                ('icone', models.CharField(default='fas fa-download', max_length=100, verbose_name='Ícone')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Recurso de Desastre',
                'verbose_name_plural': 'Recursos de Desastres',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TipoDesastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('geologico', 'Geológico'), ('meteorologico', 'Meteorológico'), ('hidrologico', 'Hidrológico'), ('climatico', 'Climático'), ('biologico', 'Biológico'), ('tecnologico', 'Tecnológico')], default='geologico', max_length=50, verbose_name='Categoria')),
                ('subcategoria', models.CharField(max_length=100, verbose_name='Subcategoria')),
                ('escala_medicao', models.CharField(max_length=100, verbose_name='Escala de Medição')),
                ('velocidade_propagacao', models.CharField(max_length=100, verbose_name='Velocidade de Propagação')),
                ('duracao_media', models.CharField(max_length=100, verbose_name='Duração Média')),
                ('desastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='app.desastre', verbose_name='Desastre')),
            ],
            options={
                'verbose_name': 'Tipo de Desastre',
                'verbose_name_plural': 'Tipos de Desastres',
            },
        ),
    ]
